### ISSUE TITLE
Possible mistake in CV

### ISSUE THREAD

**Issue by jhrcook** [YTLogos/CV#1]
Hello,

I was just looking at your CV and saw "Analysis of oilseed Rape". If I'm not mistaken, I think you were trying to say "rapeseed oil". Hopefully this is helpful, if not, feel free to ignore it.

 \- Josh Cook

**Comment by YTLogos** [comment]
> Hello,
> 
> I was just looking at your CV and saw "Analysis of oilseed Rape". If I'm not mistaken, I think you were trying to say "rapeseed oil". Hopefully this is helpful, if not, feel free to ignore it.
> 
> - Josh Cook

Hi Josh！
Thanks for your friendly reminder. I have replaced it with Brassica napus L. "Rape" is not a good word in English, so we call Brassica napus as rapeseed.
